# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20241113-182745-tractable-monument

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: ru

pipeline:
  # # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
  # # If you'd like to customize it, uncomment and adjust the pipeline.
  # # See https://rasa.com/docs/rasa/tuning-your-model for more information.
  #   - name: WhitespaceTokenizer
  #   - name: RegexFeaturizer
  #   - name: LexicalSyntacticFeaturizer
  #   - name: CountVectorsFeaturizer
  #   - name: CountVectorsFeaturizer
- name: WhitespaceTokenizer                  # Токенизатор, разделяющий текст по пробелам
- name: RegexFeaturizer                      # Извлечение признаков с помощью регулярных выражений
- name: LexicalSyntacticFeaturizer           # Лексико-синтаксический анализатор
- name: CountVectorsFeaturizer               # Извлечение признаков по частоте слов
    #     analyzer: char_wb
  analyzer: "char_wb"                        # Символьные N-граммы
    #     min_ngram: 1
  min_ngram: 1
    #     max_ngram: 4
  max_ngram: 2                               # Уменьшены размеры N-грамм для ускорения

  # Подключение предобученной модели трансформера (BERT)
- name: "LanguageModelFeaturizer"
  model_name: "bert"                         # Модель BERT для русского языка
  model_weights: "bert-base-cased"            # Весы модели BERT
  cache_dir: null

- name: DIETClassifier                        # Классификатор на базе DIET
  epochs: 1                                   # Минимальное количество эпох обучения
  transformer_size: 32                        # Минимальный размер слоя трансформера
  number_of_transformer_layers: 1             # Один слой трансформера
  use_masked_language_model: false            # Отключено для ускорения
  batch_strategy: "balanced"
  hidden_layers_sizes:
    text: [32]                                # Минимальные скрытые слои

- name: EntitySynonymMapper                   # Маппер синонимов сущностей
- name: ResponseSelector                      # Минимальный выбор ответа
  epochs: 1                                   # Минимальное количество эпох обучения
#   - name: DIETClassifier
#     epochs: 100
#     constrain_similarities: true
#   - name: EntitySynonymMapper
#   - name: ResponseSelector
#     epochs: 100
#     constrain_similarities: true
#   - name: FallbackClassifier
#     threshold: 0.3
#     ambiguity_threshold: 0.1

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
- name: MemoizationPolicy
  max_history: 2                            # Минимальная история
- name: RulePolicy
- name: TEDPolicy
  max_history: 2                            # Минимальное количество шагов в истории
  epochs: 1                                 # Минимальное количество эпох обучения
  constrain_similarities: true
# onfiguration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy
#   - name: RulePolicy
#   - name: UnexpecTEDIntentPolicy
#     max_history: 5
#     epochs: 100
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#     constrain_similarities: true
